### ISSUE TITLE
fasta2co step duration?

### ISSUE THREAD

**Issue by lmolokin** [yhg926/co-phylog#3]
Hi. Approximately how long does the fasta2co step take? I left the process running overnight on a single 44Mb assembly fasta file and it's still running. Should it take less than a day? Several days? I'd like to make a phylogeny of 40 or so assemblies so I'm trying to get a sense of how long this might thake.

Thanks.

**Comment by yhg926** [comment]
for 44M fasta file， we recommend using half context length of 10；you may need to change this parameter. Normally fasta2co step only takes few seconds.Best，Huiguang YiSent from my iPhoneOn Aug 8, 2023, at 10:43 PM, Aleksey Molokin ***@***.***> wrote:﻿
Hi. Approximately how long does the fasta2co step take? I left the process running overnight on a single 44Mb assembly fasta file and it's still running. Should it take less than a day? Several days? I'd like to make a phylogeny of 40 or so assemblies so I'm trying to get a sense of how long this might thake.
Thanks.

**Comment by lmolokin** [comment]
Thank you for your reply. 

Could you elaborate on what you mean by "context length" and how I would change its value?

Thanks.

**Comment by lmolokin** [comment]
I found the following line in **ctxobj.h**

`#define HALFCTX 9`

Lowering it to 7 allows fasta2co to generate the co file in a few seconds.

**Comment by lmolokin** [comment]
Do you have an estimate of the time it would take for **co2dist** to run? Seems like it may be running into the same issue where it's been stuck on a single co file for 12+ hrs and an empty output file.

Thanks!

**Comment by yhg926** [comment]
Would you please send me your fasta files (just 2-3 files is OK) , so i
could replicate your issue and debug.
Many thanks!
Huiguang Yi

Aleksey Molokin ***@***.***> 于2023年8月9日周三 21:27写道：

**Comment by lmolokin** [comment]
Here are two you could try to run through the steps. Thanks for your help thus far!

[GCF_000769155.1_ASM76915v2_genomic.fna.gz](https://github.com/yhg926/co-phylog/files/12313658/GCF_000769155.1_ASM76915v2_genomic.fna.gz)
[GCF_002999335.1_CcayRef3_genomic.fna.gz](https://github.com/yhg926/co-phylog/files/12313661/GCF_002999335.1_CcayRef3_genomic.fna.gz)

**Comment by yhg926** [comment]
We identified the issue to be the file size exceed the default hashsize. we have fix the bug.
Now, just recompile the codes with HASHSIZE redefined:
gcc fasta2co_v18.3.c -O6 -Wall -o fasta2co -DHASHSIZE=134217689
gcc co2dist2.c -O6 -Wall -o co2dist -DHASHSIZE=134217689 
=======
set HALFCTX to 9 or 10 in ctxobj.h. for your case 7 is not a good choice.
 
the running time per genome only take seconds.

**Comment by lmolokin** [comment]
Can confirm both steps work with the larger hash size. Thanks!

In the future, if I am working with even larger genomes is there a way to determine how large the hash size should be?

**Comment by yhg926** [comment]
just use hashsize larger than the genome size，better be a prime number.Sent from my iPhoneOn Aug 18, 2023, at 11:52 PM, Aleksey Molokin ***@***.***> wrote:﻿
Can confirm both steps work with the larger hash size. Thanks!
In the future, if I am working with even larger genomes is there a way to determine how large the hash size should be?

**Comment by lmolokin** [comment]
Got it. Thanks again!
